## This Notebook Covers
- Scraping the profiles of the student data from Yocket for 29 Universities
- The dataset has graduate student details for Admit and Reject for Computer Science Deaprtment

In [ ]:
# importing libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import pandas as pd
from selenium import webdriver
import time
from bs4 import BeautifulSoup
from selenium.webdriver.chrome.options import Options
from fake_useragent import UserAgent

In [8]:
# creating global varibale for storing of the specific university profile
temp1=[]

#### Scraping Edulix data for multiple university
- we will use the entire scraped university list to get the profile data for the 29 Universities

In [15]:
options = Options()
ua = UserAgent()
userAgent = ua.random

options.add_argument(f'user-agent={userAgent}')
driver = webdriver.Chrome(chrome_options=options, executable_path = 'chromedriver.exe')

driver.get('https://www.edulix.com/')
time.sleep(30)
driver.get('https://www.edulix.com/' + 'share-profile/93397')
#page = requests.get("https://yocket.in/applications-admits-rejects/26228-null/2?page=" + str(i))
html = driver.page_source
soup = BeautifulSoup(html)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [21]:
name_containers = soup.select('.form-control-static')
for i in name_containers:
    k =(i.text)
    t=[i for i in k.strip().split("\n") if len(i) is not 0]
    temp1.append(t)
    #time.sleep(15)
r1= pd.DataFrame(temp1)

In [23]:
name_containers[0].text

'girishpatni'

In [25]:
options = Options()
ua = UserAgent()
userAgent = ua.random

options.add_argument(f'user-agent={userAgent}')
driver = webdriver.Chrome(chrome_options=options, executable_path = 'chromedriver.exe')

driver.get('https://www.edulix.com/')
time.sleep(30)
driver.get('https://www.edulix.com/' + 'student-profiles')
time.sleep(50)
#page = requests.get("https://yocket.in/applications-admits-rejects/26228-null/2?page=" + str(i))
html = driver.page_source
soup = BeautifulSoup(html)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [38]:
url_containers = soup.select('#jqGrid')
profiles=[]
for i in url_containers[0].find_all("a", href=True):
    print(i['href'])

/share-profile/51243
/share-profile/60418
/share-profile/70921
/share-profile/71696
/share-profile/75778
/share-profile/75786
/share-profile/82435
/share-profile/83359
/share-profile/85497
/share-profile/86456
/share-profile/87421
/share-profile/89467
/share-profile/93397
/share-profile/101376
/share-profile/103171
/share-profile/105929
/share-profile/107990
/share-profile/109798
/share-profile/111411
/share-profile/112977
/share-profile/113399
/share-profile/116676
/share-profile/120608
/share-profile/121989
/share-profile/124203
/share-profile/124869
/share-profile/125624
/share-profile/125663
/share-profile/125670
/share-profile/126794

In [43]:
find_jobs = driver.find_element_by_xpath(r'//*[@id="next_jqGridPager"]/span')
driver.execute_script('arguments[0].click();',find_jobs)
html1 = driver.page_source
soup = BeautifulSoup(html1)
url_containers = soup.select('#jqGrid')

In [46]:
profiles=[]
for i in url_containers[0].find_all("a", href=True):
    print(i['href'])

/share-profile/144637
/share-profile/144671
/share-profile/146258
/share-profile/146598
/share-profile/146980
/share-profile/147221
/share-profile/148111
/share-profile/148446
/share-profile/148512
/share-profile/148919
/share-profile/149006
/share-profile/150166
/share-profile/151139
/share-profile/151245
/share-profile/152063
/share-profile/152775
/share-profile/153437
/share-profile/153612
/share-profile/153636
/share-profile/153707
/share-profile/153866
/share-profile/154143
/share-profile/154145
/share-profile/154476
/share-profile/154690
/share-profile/155114
/share-profile/155433
/share-profile/155549
/share-profile/156261
/share-profile/156286

In [98]:
def get_student_profile_urls():
    options = Options()
    ua = UserAgent()
    userAgent = ua.random
    options.add_argument(f'user-agent={userAgent}')
    driver = webdriver.Chrome(chrome_options=options, executable_path = 'chromedriver.exe')
    driver.get('https://www.edulix.com/')
    time.sleep(50)
    driver.get('https://www.edulix.com/' + 'student-profiles')
    time.sleep(50)
    #page = requests.get("https://yocket.in/applications-admits-rejects/26228-null/2?page=" + str(i))
    profile_urls = []
    for i in range(1,19):
        html = driver.page_source
        soup = BeautifulSoup(html)
        url_containers = soup.select('#jqGrid')
        for i in url_containers[0].find_all("a", href=True):
            profile_urls.append("https://www.edulix.com"+i['href'])
        find_profiles = driver.find_element_by_xpath(r'//*[@id="next_jqGridPager"]/span')
        driver.execute_script('arguments[0].click();',find_profiles)
    return profile_urls

In [49]:
neu_profiles = get_student_profile_urls()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [53]:
neu_profiles_df = pd.DataFrame({"profiles":neu_profiles})

In [55]:
neu_profiles_df.to_csv("neu_profiles_df.csv")

In [58]:
asu_profiles = get_student_profile_urls()
asu_profiles_df = pd.DataFrame({"profiles":asu_profiles})
asu_profiles_df.to_csv("asu_profiles_df.csv")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [ ]:
asu_profiles = get_student_profile_urls()
asu_profiles_df = pd.DataFrame({"profiles":asu_profiles})
asu_profiles_df.to_csv("asu_profiles_df.csv")

In [69]:
len(asu_profiles)

1346

In [61]:
iitc_profiles = get_student_profile_urls()
iitc_profiles_df = pd.DataFrame({"profiles":iitc_profiles})
iitc_profiles_df.to_csv("iitc_profiles_df.csv")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [62]:
len(iitc_profiles)

387

In [66]:
syracuse_profiles = get_student_profile_urls()
syracuse_profiles_df = pd.DataFrame({"profiles":syracuse_profiles})
syracuse_profiles_df.to_csv("syracuse_profiles_df.csv")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [67]:
len(syracuse_profiles)

466

In [72]:
utd_profiles = get_student_profile_urls()
utd_profiles_df = pd.DataFrame({"profiles":utd_profiles})
utd_profiles_df.to_csv("utd_profiles_df.csv")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [73]:
len(utd_profiles)

1470

In [75]:
uta_profiles = get_student_profile_urls()
uta_profiles_df = pd.DataFrame({"profiles":uta_profiles})
uta_profiles_df.to_csv("uta_profiles_df.csv")
len(uta_profiles)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

489

In [77]:
#naveenj11695@gmail.com
clemson_profiles = get_student_profile_urls()
clemson_profiles_df = pd.DataFrame({"profiles":clemson_profiles})
clemson_profiles_df.to_csv("clemson_profiles_df.csv")
len(clemson_profiles)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

199

In [79]:
rit_profiles = get_student_profile_urls()
rit_profiles_df = pd.DataFrame({"profiles":rit_profiles})
rit_profiles_df.to_csv("rit_profiles_df.csv")
len(rit_profiles)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

561

In [ ]:
usc_profiles = get_student_profile_urls()
usc_profiles_df = pd.DataFrame({"profiles":usc_profiles})
usc_profiles_df.to_csv("usc_profiles_df.csv")

In [82]:
len(usc_profiles)

730

In [84]:
mtu_profiles = get_student_profile_urls()
mtu_profiles_df = pd.DataFrame({"profiles":mtu_profiles})
mtu_profiles_df.to_csv("mtu_profiles_df.csv")
len(mtu_profiles)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

291

In [90]:
nyu_profiles = get_student_profile_urls()
nyu_profiles_df = pd.DataFrame({"profiles":nyu_profiles})
nyu_profiles_df.to_csv("nyu_profiles_df.csv")
len(nyu_profiles)

158

In [91]:
iub_profiles = get_student_profile_urls()
iub_profiles_df = pd.DataFrame({"profiles":iub_profiles})
iub_profiles_df.to_csv("iub_profiles_df.csv")
len(iub_profiles)

310

In [93]:
rutgers_profiles = get_student_profile_urls()
rutgers_profiles_df = pd.DataFrame({"profiles":rutgers_profiles})
rutgers_profiles_df.to_csv("rutgers_profiles_df.csv")
len(rutgers_profiles)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

133

In [95]:
sjsu_profiles = get_student_profile_urls()
sjsu_profiles_df = pd.DataFrame({"profiles":sjsu_profiles})
sjsu_profiles_df.to_csv("sjsu_profiles_df.csv")
len(sjsu_profiles_df)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

378

In [99]:
ufl_profiles = get_student_profile_urls()
ufl_profiles_df = pd.DataFrame({"profiles":ufl_profiles})
ufl_profiles_df.to_csv("ufl_profiles_df.csv")
len(ufl_profiles_df)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

534

In [103]:
total_profiles_urls = neu_profiles_df.append(asu_profiles_df).append(iitc_profiles_df).append(syracuse_profiles_df).append(utd_profiles_df).append(uta_profiles_df).append(clemson_profiles_df).append(rit_profiles_df).append(usc_profiles_df).append(mtu_profiles_df).append(nyu_profiles_df).append(iub_profiles_df).append(rutgers_profiles_df).append(sjsu_profiles_df).append(ufl_profiles_df)

In [106]:
total_profiles_urls.reset_index(drop=True,inplace=True)

In [112]:
total_profiles_urls=total_profiles_urls.drop_duplicates()

In [113]:
total_profiles_urls.reset_index(drop=True,inplace=True)

In [ ]:
options = Options()
ua = UserAgent()
userAgent = ua.random

options.add_argument(f'user-agent={userAgent}')
driver = webdriver.Chrome(chrome_options=options, executable_path = 'chromedriver.exe')

driver.get('https://www.edulix.com/')
time.sleep(30)
driver.get('https://www.edulix.com/' + 'share-profile/93397')
#page = requests.get("https://yocket.in/applications-admits-rejects/26228-null/2?page=" + str(i))
html = driver.page_source
soup = BeautifulSoup(html)

In [115]:
copy=name_containers

In [178]:
copy[37].text

'Masters'

In [235]:
records = [["username","firstname","undergrad_college","undergrad_major","undergrad_gpa","country","gre_quant","gre_verbal","gre_awa","toefl_list","toefl_spk","toefl_rd","toefl_wrt","ielts_list","ielts_spk","ielts_rd","program","university","major","term","year","status"]]

In [225]:
username = copy[0].text
firstname = copy[1].text
undergrad_college = copy[8].text
undergrad_major = copy[9].text
undergrad_gpa = copy[10].text
country = copy[11].text
gre_quant = copy[12].text
gre_verbal = copy[13].text
gre_total = gre_quant+gre_verbal
gre_awa = copy[14].text
toefl_list = copy[16].text
toefl_spk = copy[17].text
toefl_rd = copy[18].text
toefl_wrt = copy[19].text
ielts_list = copy[21].text
ielts_spk = copy[22].text
ielts_rd = copy[23].text
ielts_wrt = copy[24].text
program = copy[31].text
university = copy[32].text
major = copy[33].text
term = copy[34].text
year = copy[35].text
status = copy[36].text
records.append([username,firstname,undergrad_college,undergrad_major,undergrad_gpa,country,gre_quant,gre_verbal,gre_awa,toefl_list,toefl_spk,toefl_rd,toefl_wrt,ielts_list,ielts_spk,ielts_rd,program,university,major,term,year,status])

In [226]:
copy[42+6]

In [227]:
for i in range(0,len(copy[37:]),6):
    username = copy[0].text
    firstname = copy[1].text
    undergrad_college = copy[8].text
    undergrad_major = copy[9].text
    undergrad_gpa = copy[10].text
    country = copy[11].text
    gre_quant = copy[12].text
    gre_verbal = copy[13].text
    gre_awa = copy[14].text
    toefl_list = copy[16].text
    toefl_spk = copy[17].text
    toefl_rd = copy[18].text
    toefl_wrt = copy[19].text
    ielts_list = copy[21].text
    ielts_spk = copy[22].text
    ielts_rd = copy[23].text
    ielts_wrt = copy[24].text
    program = copy[37+i].text
    university = copy[38+i].text
    major = copy[39+i].text
    term = copy[40+i].text
    year = copy[41+i].text
    status = copy[42+i].text
    records.append([username,firstname,undergrad_college,undergrad_major,undergrad_gpa,country,gre_quant,gre_verbal,gre_awa,toefl_list,toefl_spk,toefl_rd,toefl_wrt,ielts_list,ielts_spk,ielts_rd,program,university,major,term,year,status])

In [229]:
df = pd.DataFrame(records[1:],columns=records[0])

In [265]:
def scrape_admissions_data(profile_urls):
    count=0
    options = Options()
    ua = UserAgent()
    userAgent = ua.random
    options.add_argument(f'user-agent={userAgent}')
    driver = webdriver.Chrome(chrome_options=options, executable_path = 'chromedriver.exe')
    driver.get('https://www.edulix.com/auth/login')
    time.sleep(25)
    for each in profile_urls['profiles'].tolist():
        try:
            driver.get(each)
            #page = requests.get("https://yocket.in/applications-admits-rejects/26228-null/2?page=" + str(i))
            html = driver.page_source
            soup = BeautifulSoup(html)
            name_containers = soup.select('.form-control-static')
            copy=name_containers
            username = copy[0].text
            firstname = copy[1].text
            undergrad_college = copy[8].text
            undergrad_major = copy[9].text
            undergrad_gpa = copy[10].text
            country = copy[11].text
            gre_quant = copy[12].text
            gre_verbal = copy[13].text
            gre_total = gre_quant+gre_verbal
            gre_awa = copy[14].text
            toefl_list = copy[16].text
            toefl_spk = copy[17].text
            toefl_rd = copy[18].text
            toefl_wrt = copy[19].text
            ielts_list = copy[21].text
            ielts_spk = copy[22].text
            ielts_rd = copy[23].text
            ielts_wrt = copy[24].text
            program = copy[31].text
            university = copy[32].text
            major = copy[33].text
            term = copy[34].text
            year = copy[35].text
            status = copy[36].text
            records.append([username,firstname,undergrad_college,undergrad_major,undergrad_gpa,country,gre_quant,gre_verbal,gre_awa,toefl_list,toefl_spk,toefl_rd,toefl_wrt,ielts_list,ielts_spk,ielts_rd,program,university,major,term,year,status])
            count+=1
            print('records generated: '+str(count))
        except:
            continue
        for i in range(0,len(copy[37:]),6):
            try:
                username = copy[0].text
                firstname = copy[1].text
                undergrad_college = copy[8].text
                undergrad_major = copy[9].text
                undergrad_gpa = copy[10].text
                country = copy[11].text
                gre_quant = copy[12].text
                gre_verbal = copy[13].text
                gre_awa = copy[14].text
                toefl_list = copy[16].text
                toefl_spk = copy[17].text
                toefl_rd = copy[18].text
                toefl_wrt = copy[19].text
                ielts_list = copy[21].text
                ielts_spk = copy[22].text
                ielts_rd = copy[23].text
                ielts_wrt = copy[24].text
                program = copy[37+i].text
                university = copy[38+i].text
                major = copy[39+i].text
                term = copy[40+i].text
                year = copy[41+i].text
                status = copy[42+i].text
                records.append([username,firstname,undergrad_college,undergrad_major,undergrad_gpa,country,gre_quant,gre_verbal,gre_awa,toefl_list,toefl_spk,toefl_rd,toefl_wrt,ielts_list,ielts_spk,ielts_rd,program,university,major,term,year,status])
                count+=1
                print('records generated: '+str(count))
            except:
                continue

In [268]:
admission_records = pd.DataFrame(records[1:],columns=records[0])

In [274]:
admission_records.loc[admission_records['university']=='Northeastern University',:]['status'].value_counts()

Admitted    660
Applied     262
Rejected    253
Name: status, dtype: int64

In [275]:
admission_records.to_csv('.\data\Edulix_admission_records.csv')

In [278]:
admission_records.drop_duplicates(inplace=True)

In [280]:
admission_records.reset_index(drop=True,inplace=True)

In [293]:
colleges = admission_records.university.tolist()

In [296]:
required_colleges = ['Northeastern University','Illinois Institute of Technology','Michigan Technological University','Rochester Institute of Technology','University of Southern California','University of North Carolina Charlotte','University of Texas Arlington','University of Texas Dallas','Syracuse University','Clemson University','New York University','Indiana University-Bloomington','Rutgers University New Brunswick/Piscataway','San Jose State University','University of Florida']

In [316]:
adm = pd.DataFrame()
for college in colleges:
    print(college)
    boolean = (admission_records['university']== college) & ((admission_records['major'] == 'Computer Science') | (admission_records['major'] == 'CS'))
    print(admission_records.loc[boolean,:]['status'].value_counts())
    print('===========================================================================================')

North Carolina State University
Rejected    292
Admitted    166
Applied      82
Name: status, dtype: int64
===========================================================================================
University of North Carolina Charlotte
Admitted    114
Rejected     79
Applied      27
Name: status, dtype: int64
===========================================================================================
University of Arizona
Rejected    34
Admitted     8
Applied      4
Name: status, dtype: int64
===========================================================================================
University of Maryland College Park
Rejected    56
Applied      5
Admitted     2
Name: status, dtype: int64
===========================================================================================
University of Texas Austin
Rejected    77
Applied     13
Admitted     4
Name: status, dtype: int64
===========================================================================================
Texas A and M University College Station
Rejected    136
Applied     112
Admitted     28
Name: status, dtype: int64
===========================================================================================
Georgia Institute of Technology
Rejected    216
Applied      39
Admitted     13
Name: status, dtype: int64
===========================================================================================
University of Utah
Rejected    79
Admitted    35
Applied     28
Name: status, dtype: int64
===========================================================================================
Northeastern University
Admitted    316
Rejected    164
Applied     112
Name: status, dtype: int64
===========================================================================================
University of Colorado Boulder
Rejected    36
Admitted    21
Applied     11
Name: status, dtype: int64
===========================================================================================
University of Oklahoma
Admitted    4
Name: status, dtype: int64
===========================================================================================
SUNY Stony Brook
Rejected    278
Admitted    145
Applied     144
Name: status, dtype: int64
===========================================================================================
Oklahoma State University Stillwater
Admitted    14
Rejected     5
Applied      5
Name: status, dtype: int64
===========================================================================================
University of Illinois Chicago
Rejected    160
Admitted     99
Applied      65
Name: status, dtype: int64
===========================================================================================
University of Nebraska Omaha
Admitted    2
Applied     1
Name: status, dtype: int64
===========================================================================================
University of South Florida
Rejected    14
Admitted     9
Applied      8
Name: status, dtype: int64
===========================================================================================
University of Illinois Urbana-Champaign
Rejected    74
Admitted    20
Applied     11
Name: status, dtype: int64
===========================================================================================
Rutgers University New Brunswick/Piscataway
Rejected    65
Applied     51
Admitted    32
Name: status, dtype: int64
===========================================================================================
University of Florida
Rejected    226
Admitted    168
Applied      92
Name: status, dtype: int64
===========================================================================================
University of Cincinnati
Admitted    32
Applied     30
Rejected    13
Name: status, dtype: int64
===========================================================================================
SUNY Buffalo
Admitted    207
Applied     171
Rejected    155
Name: status, dtype: int64
===========================================================================================
University of Texas Dallas
Admitted    495
Rejected    151
Applied      49
Name: status, dtype: int64
===========================================================================================
Syracuse University
Admitted    122
Rejected     95
Applied      24
Name: status, dtype: int64
===========================================================================================
Santa Clara University
Admitted    15
Applied      5
Rejected     3
Name: status, dtype: int64
===========================================================================================
University of Southern California
Applied     286
Admitted    259
Rejected    117
Name: status, dtype: int64
===========================================================================================
Rochester Institute of Technology
Admitted    233
Applied      18
Rejected      8
Name: status, dtype: int64
===========================================================================================
Arizona State University
Admitted    413
Rejected    148
Applied     107
Name: status, dtype: int64
===========================================================================================
Virginia Polytechnic Institute and State University
Rejected    65
Applied     31
Admitted     8
Name: status, dtype: int64
===========================================================================================
University of Massachusetts Amherst
Rejected    90
Admitted    11
Applied     10
Name: status, dtype: int64
===========================================================================================
Indiana University-Bloomington
Admitted    186
Rejected     72
Applied      67
Name: status, dtype: int64
===========================================================================================
University of North Carolina Chapel Hill
Applied     16
Rejected    13
Admitted     1
Name: status, dtype: int64
===========================================================================================
Pennsylvania State University University Park [main campus]
Rejected    29
Applied      6
Admitted     3
Name: status, dtype: int64
===========================================================================================
University of Minnesota Twin Cities
Rejected    85
Applied     82
Admitted    23
Name: status, dtype: int64
===========================================================================================
Ohio State University Columbus
Rejected    60
Admitted    45
Applied     23
Name: status, dtype: int64
===========================================================================================
San Jose State University
Admitted    153
Applied      84
Rejected     34
Name: status, dtype: int64
===========================================================================================
Polytechnic University of New York
Admitted    88
Applied     48
Rejected    30
Name: status, dtype: int64
===========================================================================================
University of California Riverside
Applied     16
Rejected    11
Admitted     7
Name: status, dtype: int64
===========================================================================================
Illinois Institute of Technology
Admitted    116
Rejected     24
Applied      12
Name: status, dtype: int64
===========================================================================================
University of Missouri Rolla
Admitted    9
Rejected    4
Applied     3
Name: status, dtype: int64
===========================================================================================
University of Michigan Ann Arbor
Rejected    22
Applied      7
Admitted     3
Name: status, dtype: int64
===========================================================================================
Carnegie Mellon University
Rejected    57
Admitted    39
Applied      8
Name: status, dtype: int64
===========================================================================================
Johns Hopkins University
Admitted    12
Rejected     8
Applied      5
Name: status, dtype: int64
===========================================================================================
Columbia University
Rejected    33
Admitted    18
Applied     16
Name: status, dtype: int64
===========================================================================================
University of California Irvine
Rejected    144
Applied      93
Admitted     17
Name: status, dtype: int64
===========================================================================================
New York University
Admitted    53
Rejected    31
Applied     16
Name: status, dtype: int64
===========================================================================================
Clemson University
Rejected    25
Admitted    23
Applied     13
Name: status, dtype: int64
===========================================================================================
Southern Methodist University
Applied     2
Admitted    2
Rejected    1
Name: status, dtype: int64
===========================================================================================
Florida International University
Admitted    3
Applied     3
Name: status, dtype: int64
===========================================================================================
Duke University
Rejected    4
Applied     1
Name: status, dtype: int64
===========================================================================================
George Washington University at Mount Vernon College
Admitted    7
Rejected    2
Name: status, dtype: int64
===========================================================================================
SUNY College at Buffalo [Buffalo State College]
Applied     18
Admitted    13
Rejected     7
Name: status, dtype: int64
===========================================================================================
Western Michigan University
Admitted    1
Name: status, dtype: int64
===========================================================================================
Cornell University
Rejected    37
Admitted    16
Applied     16
Name: status, dtype: int64
===========================================================================================
Iowa State University
Rejected    62
Admitted    22
Applied     16
Name: status, dtype: int64
===========================================================================================
University of Texas Arlington
Admitted    140
Applied      29
Rejected     25
Name: status, dtype: int64
===========================================================================================
Dartmouth College
Admitted    1
Applied     1
Name: status, dtype: int64
===========================================================================================
Case Western Reserve University
Admitted    1
Applied     1
Name: status, dtype: int64
===========================================================================================
George Mason University
Admitted    42
Applied     21
Rejected    21
Name: status, dtype: int64
===========================================================================================
University of California Los Angeles
Rejected    59
Applied     19
Admitted    12
Name: status, dtype: int64
===========================================================================================
University of California San Diego
Rejected    92
Applied     25
Admitted    16
Name: status, dtype: int64
===========================================================================================
University of California Davis
Applied     20
Rejected    16
Admitted     2
Name: status, dtype: int64
===========================================================================================
University of Maryland Baltimore County
Admitted    23
Rejected    18
Applied     15
Name: status, dtype: int64
===========================================================================================
University of Michigan Dearborn
Series([], Name: status, dtype: int64)
===========================================================================================
University of Wisconsin Madison
Rejected    55
Applied      5
Admitted     3
Name: status, dtype: int64
===========================================================================================
SUNY Binghamton
Admitted    48
Applied     14
Rejected    11
Name: status, dtype: int64
===========================================================================================
Auburn University
Admitted    2
Applied     2
Rejected    2
Name: status, dtype: int64
===========================================================================================
University of Notre Dame
Admitted    1
Rejected    1
Name: status, dtype: int64
===========================================================================================
Michigan Technological University
Admitted    10
Rejected     5
Applied      1
Name: status, dtype: int64
===========================================================================================
University of California Santa Cruz
Rejected    27
Admitted    10
Applied      1
Name: status, dtype: int64
===========================================================================================
Texas Tech University
Admitted    10
Applied      7
Name: status, dtype: int64
===========================================================================================
New Jersey Institute of Technology
Admitted    44
Applied     10
Rejected     2
Name: status, dtype: int64
===========================================================================================
University of Pittsburgh Bradford
Rejected    6
Applied     4
Admitted    1
Name: status, dtype: int64
===========================================================================================
Wichita State University
Rejected    1
Name: status, dtype: int64
===========================================================================================
University of New Mexico
Admitted    5
Rejected    2
Name: status, dtype: int64
===========================================================================================
University of California Santa Barbara
Rejected    45
Applied      9
Admitted     1
Name: status, dtype: int64
===========================================================================================
Pennsylvania State University
Rejected    18
Applied     12
Admitted     2
Name: status, dtype: int64
===========================================================================================
Rutgers University
Rejected    15
Applied     11
Admitted    10
Name: status, dtype: int64
===========================================================================================
University of Missouri Columbia
Admitted    4
Applied     3
Rejected    1
Name: status, dtype: int64
===========================================================================================
University of Akron
Applied     6
Admitted    2
Rejected    1
Name: status, dtype: int64
===========================================================================================
Purdue University
Rejected    44
Applied     11
Admitted     7
Name: status, dtype: int64
===========================================================================================
Florida State University
Admitted    13
Applied     13
Rejected     5
Name: status, dtype: int64
===========================================================================================
Boston University
Admitted    7
Applied     3
Rejected    1
Name: status, dtype: int64
===========================================================================================
Louisiana State University Baton Rouge
Admitted    6
Applied     2
Rejected    1
Name: status, dtype: int64
===========================================================================================
Northwestern University
Applied     12
Rejected     4
Admitted     2
Name: status, dtype: int64
===========================================================================================
University of Pennsylvania
Rejected    54
Applied     15
Admitted    14
Name: status, dtype: int64
===========================================================================================
Pennsylvania State University Harrisburg
Admitted    6
Applied     1
Rejected    1
Name: status, dtype: int64
===========================================================================================
Stevens Institute of Technology
Admitted    18
Rejected     2
Applied      1
Name: status, dtype: int64
===========================================================================================
George Washington University Virginia Campus
Applied    1
Name: status, dtype: int64
===========================================================================================
California State University Long Beach
Applied     34
Admitted    17
Rejected     7
Name: status, dtype: int64
===========================================================================================
Rensselaer Polytechnic Institute
Rejected    7
Admitted    1
Applied     1
Name: status, dtype: int64
===========================================================================================
Colorado State University
Admitted    30
Rejected    15
Applied      5
Name: status, dtype: int64
===========================================================================================
University of Iowa
Admitted    3
Rejected    1
Applied     1
Name: status, dtype: int64
===========================================================================================
Wayne State University
Admitted    3
Rejected    2
Name: status, dtype: int64
===========================================================================================
SUNY Institute of Technology at Utica/Rome
Series([], Name: status, dtype: int64)
===========================================================================================
University of Dallas
Rejected    4
Applied     2
Admitted    1
Name: status, dtype: int64
===========================================================================================
University of Connecticut
Admitted    1
Name: status, dtype: int64
===========================================================================================
San Diego State University
Rejected    42
Admitted    29
Applied     16
Name: status, dtype: int64
===========================================================================================
University of Washington
Rejected    5
Applied     4
Name: status, dtype: int64
===========================================================================================
Oregon State University
Rejected    22
Applied      8
Admitted     2
Name: status, dtype: int64
===========================================================================================
University of Kansas
Admitted    11
Rejected     4
Applied      3
Name: status, dtype: int64
===========================================================================================
Worcester Polytechnic Institute
Admitted    6
Rejected    4
Applied     1
Name: status, dtype: int64
===========================================================================================
University of California Berkeley
Rejected    21
Admitted     1
Applied      1
Name: status, dtype: int64
===========================================================================================
California State University Northridge
Admitted    1
Rejected    1
Name: status, dtype: int64
===========================================================================================
University of Central Florida
Admitted    10
Applied      3
Rejected     2
Name: status, dtype: int64
===========================================================================================
Old Dominion University
Admitted    2
Name: status, dtype: int64
===========================================================================================
University of Nebraska Lincoln
Admitted    4
Applied     2
Rejected    1

In [315]:
adm = pd.DataFrame()
for college in required_colleges:
    print(college)
    boolean = (admission_records['university']== college) & ((admission_records['major'] == 'Computer Science') | (admission_records['major'] == 'CS'))
    print(admission_records.loc[boolean,:]['status'].value_counts())
    print('===========================================================================================')

Northeastern University
Admitted    316
Rejected    164
Applied     112
Name: status, dtype: int64
===========================================================================================
Illinois Institute of Technology
Admitted    116
Rejected     24
Applied      12
Name: status, dtype: int64
===========================================================================================
Michigan Technological University
Admitted    10
Rejected     5
Applied      1
Name: status, dtype: int64
===========================================================================================
Rochester Institute of Technology
Admitted    233
Applied      18
Rejected      8
Name: status, dtype: int64
===========================================================================================
University of Southern California
Applied     286
Admitted    259
Rejected    117
Name: status, dtype: int64
===========================================================================================
University of North Carolina Charlotte
Admitted    114
Rejected     79
Applied      27
Name: status, dtype: int64
===========================================================================================
University of Texas Arlington
Admitted    140
Applied      29
Rejected     25
Name: status, dtype: int64
===========================================================================================
University of Texas Dallas
Admitted    495
Rejected    151
Applied      49
Name: status, dtype: int64
===========================================================================================
Syracuse University
Admitted    122
Rejected     95
Applied      24
Name: status, dtype: int64
===========================================================================================
Clemson University
Rejected    25
Admitted    23
Applied     13
Name: status, dtype: int64
===========================================================================================
New York University
Admitted    53
Rejected    31
Applied     16
Name: status, dtype: int64
===========================================================================================
Indiana University-Bloomington
Admitted    186
Rejected     72
Applied      67
Name: status, dtype: int64
===========================================================================================
Rutgers University New Brunswick/Piscataway
Rejected    65
Applied     51
Admitted    32
Name: status, dtype: int64
===========================================================================================
San Jose State University
Admitted    153
Applied      84
Rejected     34
Name: status, dtype: int64
===========================================================================================
University of Florida
Rejected    226
Admitted    168
Applied      92
Name: status, dtype: int64
===========================================================================================

In [285]:
admission_records=admission_records.loc[admission_records['undergrad_college']!="0 / 30",:]

In [320]:
admission_records=admission_records.loc[(admission_records['status']=='Applied') | (admission_records['status']=='Admitted') |(admission_records['status']=='Rejected'),: ]

In [338]:
copy = admission_records.loc[admission_records["major"].str.contains("computer science",case=False)|admission_records["major"].str.contains("CS",case=True) | admission_records["major"].str.contains("Comp Science",case=False),:]

<b> Edulix : CSV file  </b>

In [8]:
Edulix_Reject_data_all_college = pd.read_csv(r'..\..\data\Edulix_admission_records.csv')

In [11]:
Edulix_Reject_data_all_college.columns.values

array(['Unnamed: 0', 'username', 'firstname', 'undergrad_college',
       'undergrad_major', 'undergrad_gpa', 'country', 'gre_quant',
       'gre_verbal', 'gre_awa', 'toefl_list', 'toefl_spk', 'toefl_rd',
       'toefl_wrt', 'ielts_list', 'ielts_spk', 'ielts_rd', 'program',
       'university', 'major', 'term', 'year', 'status'], dtype=object)